name: ci

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.9", "3.10", "3.11"]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          sudo apt-get install libsndfile1        
          make init-dev


      - name: Run unit tests
        run: |
          export POETRY_PYPAM_TEST_NO_PLOTS=make test          
          PYPAM_TEST_NO_PLOTS= make test
